### ISSUE TITLE
Wordpress and Youtube Video Posts

### ISSUE THREAD

**Issue by qgibbs** [ionicthemes/ion2fullapp#10]
The built in Wordpress is working fine, as I edited the details and added my wordpress website. The posts on my website are coming through the app fine, but the youtube videos that are on my posts can't be seen or viewed. I believe what needs to happen is it is sanitizing the urls and not letting them be shown.

I get this error. 

`platform-browser.js:  360 WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).`

What should I do?

**Comment by djabif** [comment]
Hi, please check this answer to see if it can solve your needs https://stackoverflow.com/a/40942179/1330740
