### ISSUE TITLE
Sign In Functionality

### ISSUE THREAD

**Issue by virtualweb-at** [ionicthemes/ion2fullapp#11]
Hi,

what Code would i need when i want to authenticate the Users against a JSON-API?

There is no Code insode the doLogin() function call.

Thanks

**Comment by djabif** [comment]
Are you talking about wordpress?

**Comment by virtualweb-at** [comment]
No, i talk about what Code i have to use in **app/src/pages/login/login.ts** inside of the doLogin() function. I have an endpoint on an external URL where i want to Post User+Password and get back in JSON-Format if login was ok (and returns user data) or not.

Maybe instead i could use Firebase-Login and change the Settings that it calls my own Server instead of Firebase-Server, but i couldn't figure out how to set Firebase as Standard-Login.

**Comment by djabif** [comment]
Hi, the initial authentication screen has no functionality attached to the email/password login so as you suggest, you can copy all the code related to authentication from the firebase integration section and put it on the initial auth pages. Then you have to change the firebase connections for with your server settings.
Please let me know if you need further assistance.
