### ISSUE TITLE
Google Sign Up button does not work

### ISSUE THREAD

**Issue by sandrhymend** [ionicthemes/ion2fullapp#16]
**Describe the bug**
I tested your Live Preview on Ionic View App (Android phone)

**To Reproduce**
1. Click on Sign Up
2. Click on 'Sign Up with Google

The button did not work, it does not show any message or any results.

Does the template include this functionality?

Thanks :)

**Comment by djabif** [comment]
Cordova plugins, such as Google Connect, don't work on Ionic View. You have to test the app in a real device or in an emulator.
