### ISSUE TITLE
Getting rid of permissions (in AndroidManifest.xml)

### ISSUE THREAD

**Issue by efficienthacks** [ionicthemes/ion2fullapp#17]
I'm trying to get rid of the READ_PHONE_STATE and CALL_PHONE permissions because I don't need them.

I think if I remove some ionic native plugin, then that would solve the problem, but how do I tell which ones do I remove?  

The two that I'm trying to get rid of are:
```
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.CALL_PHONE" />

```
(I can't simply remove these lines as the build process will add them back in)

Thanks in advance.

**Comment by djabif** [comment]
To delete the cordova plugins you don't want to use, run the following:

`$ ionic cordova plugin rm name-of-plugin`

Then, make sure that there isn't any reference to that plugin both in config.xml and in package.json

**Comment by efficienthacks** [comment]
Thanks, but how do I know which one requires the "READ_PHONE_STATE"?  

Or do I have to just do trial and error until I remove the right plugin?

Edit:  I've found the offending plugin - it was one that I added when I was experimenting with something (cordova-plugin-nativeaudio) - totally not related to the theme I got from ion2fullapp

**Comment by djabif** [comment]
Thanks for the update. Closing this issue.
