### ISSUE TITLE
WordPress Category id

### ISSUE THREAD

**Issue by haydersarem** [ionicthemes/ion2fullapp#2]
How can I retrieve a single category id for WordPress ?

**Comment by djabif** [comment]
Do you want to retrieve the posts from a specific category?

**Comment by haydersarem** [comment]
yeah

**Comment by djabif** [comment]
That's already implemented on Ion2FullApp ELITE, isn't that what you are looking for?
 
![image](https://user-images.githubusercontent.com/1735814/39678297-0764ec20-5160-11e8-869b-8be16572bfcb.png)

**Comment by haydersarem** [comment]
Yeah I see, but my aim to create a new page and retrieve a single category list for example retrieve only home category with id:1

**Comment by djabif** [comment]
You can do:

```
    return this.http.get(
      environment.wordpress_rest_api_url
       + 'posts?_embed&orderby=modified' +
      + '&categories'=CATEGORY_ID)
    .map(res => res);
```

**Comment by haydersarem** [comment]
where to place that code on TS file of the page? and how about the HTML . what to change on this ?

sorry for the questions. I am new to Ionic.

Could you please give me a quick guide on this 


`   <ion-list>
      <button class="list-item" ion-item *ngFor="let category of categories" (click)="itemTapped($event, category)">
        <ion-row no-padding class="content-row one-line">
          <ion-col no-padding class="item-content">
            <h3 class="item-title">{{category.name}}</h3>
            <p class="item-description">{{category.description}}</p>
          </ion-col>
          <ion-col no-padding width-10 class="item-icon">
            <ion-icon name="arrow-forward"></ion-icon>
          </ion-col>
        </ion-row>
      </button>
    </ion-list>`

**Comment by djabif** [comment]
From `src/pages/wordpress-integration/wordpress-integration.service.ts` you can re use the   getRecentPosts(categoryId:number, page:number = 1) method, hardcoding the id of your category. 
The page param is for pagination.

Then, on src/pages/wordpress-integration/blog-feed/blog-feed.ts put you category id on YOUR_CATEGORY_ID.

`ionViewWillEnter() {
    this.wordpressService.getUser()
    .then(
      data => this.loggedUser = true,
      error => this.loggedUser = false
    );


    //if we are browsing a category
    this.categoryId = YOUR_CATEGORY_ID

    if(!(this.feed.posts.length > 0)){
      let loading = this.loadingCtrl.create();
      loading.present();

      this.wordpressService.getRecentPosts(this.categoryId)
      .subscribe(data => {

        this.feed.posts_count = Number(data.headers.get('x-wp-total'));
        this.feed.posts_pages = Number(data.headers.get('x-wp-totalpages'));

        for(let post of data.json()){
          post.excerpt.rendered = post.excerpt.rendered.split('<a')[0] + "</p>";
          this.feed.posts.push(post);
        }
        loading.dismiss();
      });
    }
  }`

**Comment by haydersarem** [comment]
Thanks a lot how about to change the view on HTML file blog-categories.html to show only the required category id. What to change here?

` <button class="list-item" ion-item *ngFor="let category of categories" (click)="itemTapped($event, category)">
        <ion-row no-padding class="content-row one-line">
          <ion-col no-padding class="item-content">
            <h3 class="item-title">{{category.name}}</h3>
            <p class="item-description">{{category.description}}</p>
          </ion-col>
          <ion-col no-padding width-10 class="item-icon">
            <ion-icon name="arrow-forward"></ion-icon>`

**Comment by haydersarem** [comment]
My aim to make a page for each category.
for example home.html ----> shows only home category posts 
for example small.html ----> shows only small category posts 

And so on. Need your help on that issue

**Comment by djabif** [comment]
You just need to retrieve only the categories you need and put them inside the `categories` list

**Comment by haydersarem** [comment]
Solved,

Thanks a lot for your perfect support
