### ISSUE TITLE
npm install show error after unzip template folder

### ISSUE THREAD

**Issue by pritiJI** [ionicthemes/ion2fullapp#20]
npm install

> grpc@1.10.1 install C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Anika Singh\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\App Developement hybrid\\Ionic\\IONIC3Template\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\App Developement hybrid\\Ionic\\IONIC3Template\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
gyp ERR! cwd C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
node-pre-gyp ERR!gyp stack     at ChildProcess.<anonymous> (C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
 node-pre-gyp ERR!ERR!  configure errorstack
     at ChildProcess.emit (events.js:182:13)
gyp node-pre-gypERR!  ERR!stack  Error: Can't find Python executable "C:\Users\Anika Singh\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
stackgyp      at maybeClose (internal/child_process.js:961:16)
ERR!node-pre-gyp  stackERR!     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
 gyp stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
node-pre-gypgyp  ERR!ERR!  Systemstack Windows_NT 10.0.17134
     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
node-pre-gypgyp  ERR!ERR!  commandstack "C:\\Program Files\\nodejs\\node.exe" "C:\\App Developement hybrid\\Ionic\\IONIC3Template\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
     at FSReqWrap.oncomplete (fs.js:152:21)
gypnode-pre-gyp ERR!  System Windows_NT 10.0.17134
ERR!gyp  cwdERR! C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc
 node-pre-gypcommand  "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\App Developement hybrid\\Ionic\\IONIC3Template\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\App Developement hybrid\\Ionic\\IONIC3Template\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown"
ERR!gyp  node -vERR! v10.9.0
 cwd C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc
node-pre-gypgyp  ERR! ERR!node -v  v10.9.0
node-pre-gyp -vgyp  v0.7.0
ERR!node-pre-gyp  ERR!node-gyp -v  v3.7.0
not okgyp
 ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\App Developement hybrid\Ionic\IONIC3Template\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Why we are getting this error....

**Comment by djabif** [comment]
Can you please run `ionic info `inside your ionic project and send me your environment info?

Did you install ionic previously? (as explained in https://ionicframework.com/docs/intro/installation/ )

**Comment by pritiJI** [comment]
yes installed and other ionic projects running properly.
$ ionic info
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (C:\Users\Anika Singh\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (0 plugins total)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Anika Singh\AppData\Local\Android\Sdk)
   NodeJS            : v10.9.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.2.0
   OS                : Windows 10

**Comment by pritiJI** [comment]
> Can you please run `ionic info`inside your ionic project and send me your environment info?
> 
> Did you install ionic previously? (as explained in https://ionicframework.com/docs/intro/installation/ )

**Comment by pritiJI** [comment]
@ionic/app-scripts : 3.2.0 in last project.
but now @ionic/ app-scripts: 3.1.8 is it right?
any issue with app-script version?
why I am getting an error in Ion2AppTemplate elite when running "npm install" in the fresh template file.
Please give me solution ....

**Comment by djabif** [comment]
you solved this, right?

**Comment by pritiJI** [comment]
yes👍
