### ISSUE TITLE
Just purchased. NPM Install failed with several errors. 

### ISSUE THREAD

**Issue by ghost** [ionicthemes/ion2fullapp#25]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

Thanks :)

**Comment by ghost** [comment]
Downloaded, unzipped, opened in vcode. NPM install - 

here is my ionic info
Robins-iMac:ion2fullapp-elite-1.1.3 robinharris$ ionic info

Ionic:

   ionic (Ionic CLI)  : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   ios-deploy : 2.0.0
   NodeJS     : v10.13.0 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS
   Xcode      : Xcode 10.0 Build version 10A255
------------------------------
another user seemed to have a similar issue but there was no indication of how he solved the problem. I am new to Ionic so I am not clear as to how to proceed. All other work on ionic 3 and 4 beta has been without such errors.
---------------------------------
errors below: 

> fsevents@1.1.3 install /Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc:../fsevents.cc6::
6In file included from :
../../nan/nan.hIn file included from :../../nan/nan.h203::
203In file included from :
../../nan/nan_new.hIn file included from :../../nan/nan_new.h189::
189:
../../nan/nan_implementation_12_inl.h:337../../nan/nan_implementation_12_inl.h::28337:: 28: warning: warning: 'New''New'  isis  deprecateddeprecated

            [-Wdeprecated-declarations][-Wdeprecated-declarations]

  return v8::StringObject::New(value).As<v8::StringObject>();  return v8::StringObject::New(value).As<v8::StringObject>();

                           ^                           ^

/Users/robinharris/.node-gyp/10.13.0/include/node/v8.h/Users/robinharris/.node-gyp/10.13.0/include/node/v8.h::50525052::33::  notenote: : 'New''New'  hashas  beenbeen  explicitlyexplicitly

            markedmarked  deprecateddeprecated  herehere

  V8_DEPRECATED("Use Isolate* version",  V8_DEPRECATED("Use Isolate* version",

  ^  ^

/Users/robinharris/.node-gyp/10.13.0/include/node/v8config.h:327:29:/Users/robinharris/.node-gyp/10.13.0/include/node/v8config.h :327:note29: : expanded fromnote : macro
expanded       'V8_DEPRECATED'from
macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
  declarator __attribute__((deprecated))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1034:44: warning: 'ToString' is deprecated [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/robinharris/.node-gyp/10.13.0/include/node/v8.h:2454:10: note: 'ToString' has been
      explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/robinharris/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1044:27: warning: 'WriteUtf8' is deprecated [-Wdeprecated-declarations]
In file included from ../fsevents.cc:6:
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);../../nan/nan.h
:                          ^1034
:44: warning: 'ToString' is/Users/robinharris/.node-gyp/10.13.0/include/node/v8.h :deprecated2658 :[-Wdeprecated-declarations]3:
 note: 'WriteUtf8' has been
      explicitly marked deprecated here
      v8::Local<v8::String> string = from->ToString();
                                           ^
  V8_DEPRECATED("Use Isolate* version",/Users/robinharris/.node-gyp/10.13.0/include/node/v8.h
:2454:  ^10
: note: 'ToString'/Users/robinharris/.node-gyp/10.13.0/include/node/v8config.h :has327 :been29
:       explicitly markednote : deprecated expandedhere from
 macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);     ^

         ^
/Users/robinharris/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:1044:27: warning: 'WriteUtf8' is deprecated [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/robinharris/.node-gyp/10.13.0/include/node/v8.h:2658:3: note: 'WriteUtf8' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/robinharris/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro
      'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from In file included from ../fsevents.cc../fsevents.cc::8585:
:
../src/methods.cc../src/methods.cc::1414::1212::  warningwarning: : 'Call''Call'  isis  deprecateddeprecated  [-Wdeprecated-declarations][-Wdeprecated-declarations]

  handler->Call(3, argv);  handler->Call(3, argv);

           ^           ^

../../nan/nan.h../../nan/nan.h::16171617::33::  notenote: : 'Call''Call'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated  herehere

  NAN_DEPRECATED inline v8::Local<v8::Value>  NAN_DEPRECATED inline v8::Local<v8::Value>

  ^  ^

../../nan/nan.h../../nan/nan.h::9898::4040::  notenote: : expandedexpanded  fromfrom  macromacro  'NAN_DEPRECATED''NAN_DEPRECATED'

# define NAN_DEPRECATED __attribute__((deprecated))# define NAN_DEPRECATED __attribute__((deprecated))

                                       ^                                       ^

4 warnings generated.
4 warnings generated.
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp  SOLINK_MODULE(target) Release/fse.node
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

> grpc@1.10.1 install /Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

  COPY /Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v64-darwin-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown"
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
gyp ERR! cwd /Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.oexec install script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.oinstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.onstall script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.ocript
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.oll script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.oc install script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_factory.ol script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o script
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.otall script
../deps/grpc/src/core/lib/compression/compression.cc:22:10: fatal error: 'grpc/compression.h' file
      not found
#include <grpc/compression.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.░⸩ ⠹ install: info lifecycle grpc@1.10.1~install: Failed to exec install script
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/compression/compression.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown"
gyp ERR! cwd /Users/robinharris/Desktop/ionic/ion2fullapp-elite-1.1.3/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robinharris/.npm/_logs/2018-11-09T18_00_33_748Z-debug.log

**Comment by djabif** [comment]
Thanks for reporting this.
We have already pushed a new version with this fixed.
The issue was fixed by updating some packages to their latest version.
You can re download the Ion2FullApp ELITE files from your account at ionicthemes.com

**Comment by ghost** [comment]
Thank you. The app is installing and I am unclear as how to know when it is completely installed. I am new to Ionic.  Once it is installed, how do I get past the flash screens and the first few screens to actually see the features of the template?

Also, I understand you are working on new templates for IONIC 4. Do you have an idea when those will be available?

Thanks,
Robin

On Nov 9, 2018, at 1:54 PM, Dayana Jabif <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reporting this.
We have already pushed a new version with this fixed.
The issue was fixed by updating some packages to their latest version.
You can re download the Ion2FullApp ELITE files from your account at ionicthemes.com<http://ionicthemes.com>

**Comment by djabif** [comment]
Hi, you can you Chrome dev tools to simulate the layout of a mobile device. Learn more in https://developers.google.com/web/tools/chrome-devtools/device-mode/#viewport
