### ISSUE TITLE
Can't run for Android

### ISSUE THREAD

**Issue by snguyen-github** [ionicthemes/ion2fullapp#26]
**Describe the bug**
I'm getting the following error when trying to run it on Android using 'ionic cordova run android --prod'

Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzex;

**To Reproduce**
1. Ran 'ionic cordova run android --prod'

**Expected behavior**
Production build to run, since I did not modify anything in the template app, just the environment variables in environment.ts

Thanks :)

**Comment by djabif** [comment]
Please run `ionic info` and include the result. 
We will check this asap and get back to you.

**Comment by snguyen-github** [comment]
![ion2fulleliteandroidrunerror](https://user-images.githubusercontent.com/1179367/51272005-c9472480-197d-11e9-9897-6567d37ac722.png)

**Comment by djabif** [comment]
Can you please include the entire log of your error? 
Did you try to run it without `--prod`, does it work?

**Comment by ghost** [comment]
@djabif I have the exact same issue after trying to do: ionic cordova run android

This occurs with or without the --prod flag.
`
Ionic:

   ionic (Ionic CLI)  : 4.8.0 (C:\Users\jpand\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : cordova-plugin-ionic 2.0.4, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (F:\NANDSDK\SDK)
   NodeJS            : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10`

Full error

`FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzex;

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 49.085 secs
(node:808) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzex;

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (C:\Users\jpand\Desktop\Projects\ion2fullapp-elite-1.1.5\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
`

**Comment by djabif** [comment]
I'm sorry you are experiencing this issue. Each development environment is different and android can get tricky with the versions and the plugins. 
We are here to help you figuring out which miss-configuration can be causing the issue. I suggest you to try what is suggested in https://forum.ionicframework.com/t/help-with-build-failed-android-ionic/94396/13, it looks like your issue.

**Comment by djabif** [comment]
The solution is to do what explained in: https://forum.ionicframework.com/t/help-with-build-failed-android-ionic/94396/13?u=ionicthemes

**Comment by ghost** [comment]
I've just found this before I checked on this issue. Thank you very much @djabif
