### ISSUE TITLE
Just purchased. NPM Install failed with several errors.

### ISSUE THREAD

**Issue by blondie63** [ionicthemes/ion2fullapp#27]
Downloaded, unzipped, opened in vs.code. NPM install - attached log file
[log-1.1.5.txt](https://github.com/ionicthemes/ion2fullapp/files/2765077/log-1.1.5.txt)

running npm audit fix i've more errors..

here is my ionic info

Ionic:

   ionic (Ionic CLI)  : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : not available
   Cordova Plugins       : not available

System:

   ios-deploy : 2.0.0
   ios-sim    : 5.0.13
   NodeJS     : v10.14.1 (/usr/local/bin/node)
   npm        : 6.5.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

Thanks :)

**Comment by djabif** [comment]
To solve those vulnerabilities please do the following. Go to `package.json` and manually change the version of `cordova-plugin-ionic-webview` to `3.0.0`. Do the same in the `config.xml` file.

Then delete node_modules folder and run `npm install` again.

Please let me know if you need further assistance.
