### ISSUE TITLE
Remove different sections in App

### ISSUE THREAD

**Issue by damianlluch** [ionicthemes/ion2fullapp#29]
Hi, one client purchased this app for your wordpress site. Three questions:

- How are remove the different sections in this App? Only I'm interested in Wordpress section.
- In Wordpress section, the comments not worked.
- How are customize the presentation for this app?

thanks!

**Comment by djabif** [comment]
Hi, documentation is in http://ion2fullapp-docs.ionicthemes.com

If you plan to use many of the pages and features offered by the template, then I suggest you to go with the option 1. 

If you only want to use some specific pages or components and you already have an existing Ionic app, then I suggest you to go with option 2 so you don't have to waste time deleting the things you don't need.

**Option 1**. Use the template app as a base to create your app
This means that the template is itself an Ionic app, so you don't need to create another app. You can use the template app as a base for your app and just delete the pages you don't want, and add what is missing.

**Option 2.** Import some pages into an existing Ionic app
Just copy the folder of the feature you want to import and its related styles.
