### ISSUE TITLE
Firebase Profile Page Incorrect

### ISSUE THREAD

**Issue by Levy4u** [ionicthemes/ion2fullapp#3]
Hello,

The pages/firebase-integration/firebase-profile/ pages are all for the "settings" page where you would change the data, not where you would see it. I'm trying to make a simple profile area that shows data from my firebase integration (which is setup as "profile" / userId / username - firstname - lastname).

**Comment by djabif** [comment]
If you don't want to allow the user to change the data you can simply change the inputs for ready only labels and remove all the code related to the Update of the components.

**Comment by Levy4u** [comment]
My problem is there is no "Profile" for the firebase profile. It is a copy of the "Settings" page.  I'm expecting to still have a profile page that i can show the data from, AND be able to update/save per user.

**Comment by djabif** [comment]
You can create another page if you need, and copy the elements you want from the other pages.

**Comment by Levy4u** [comment]
So if I setup a new firebase database and a fresh install of the downloaded template, it will create all the entries and everything for the sign-in, profile, update profile, etc? How does someone get to their profile after updating their name and clicking save?

**Comment by Levy4u** [comment]
I installed a new "app" and updated my firebase credentials but when I test it, no user data is written into the firebase database when i sign in.  I can see the user itself, but when i change the name in settings, nothing is written to the firebase database.

**Comment by djabif** [comment]
Are you getting any error message on your console? 
Is the new user stored on your Firebase Database?

**Comment by Levy4u** [comment]
Found the problem. I was looking at the "realtime" database (which was blank), not Firestore (all info in here). Thanks, I can figure it out from here. I am completely new to mobile app developing.

**Comment by djabif** [comment]
Oh! I'm glad you find out that! 
Keep up the good work 👍
