### ISSUE TITLE
Style classes not being followed.

### ISSUE THREAD

**Issue by Levy4u** [ionicthemes/ion2fullapp#8]
Hello Again,

This should be an easier bug to advise on. I'm trying to use my own CSS on an individual page but it isn't accepting what I type. It is defaulting to something else. For example, if I add text-center inline it stays left aligned, but if the row becomes 2 lines long, it becomes centered. How can I make sure the pages are looking at the .scss for themselves?

**Comment by djabif** [comment]
Did you add in the Component file the css file path?
