### ISSUE TITLE
Unable to build for Android

### ISSUE THREAD

**Issue by petrosit** [ionicthemes/ion2fullapp#9]
**Describe the bug**
I am not able to build the android version. I have installed Android Studio and JDK and set the variables:
echo $ANDROID_HOME
/Users/petros/Library/Android/sdk

This is the output I get:
(node:20599) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.
(node:20599) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The variable is set as pasted above. iOS works without any problems. 

Thanks!

**Comment by djabif** [comment]
Did you try what is suggested in https://stackoverflow.com/questions/42645285/cordova-android-sdk-not-found-make-sure-that-it-is-installed-if-it-is-not-at/42805031 ?

**Comment by petrosit** [comment]
Hi,
Yes, apparently updating the android version did the trick. But I wonder why you don't have the newer version in the template by default? I guess everyone will run into this issue?
Thanks anyways

**Comment by djabif** [comment]
Which android version did you use?
You need to have installed on your development environment (using android studio) the same sdk version that you want to use on your app.
